### ISSUE TITLE
Incorrect Part Number

### ISSUE THREAD

**Issue by bikedude880** [mspinksosu/NES-Power-Board#2]
https://github.com/mspinksosu/NES-Power-Board/blob/e8f472a10f18f6f2d27275b2264882e76d683c5a/NES%20Power%20Board.Dat#L21

This pad calls for a SPDT slide switch. This should really be a DP3T switch given the landing for the part.

Which manufacturer part is this now? Current one is SPDT and will never fit.

**Comment by bikedude880** [comment]
Following part seems to be a fit for the landing:

E-Switch EG2319

https://www.mouser.com/ProductDetail/E-Switch/EG2319?qs=f57gQzlyLirXT6sCFZHxDA%3D%3D

**Comment by bikedude880** [comment]
Please also note that R1, R2 and R3 are also missing.

**Comment by radabass** [comment]
Hi @bikedude880, the part is the EG2322

https://eu.mouser.com/ProductDetail/E-Switch/EG2322?qs=sGAEpiMZZMvGqlubrpfvZYMIW9vnpXDI

As you can see in the commit https://github.com/mspinksosu/NES-Power-Board/commit/bfbaa42909d37d6ba6428c98cd207ca6bb8a1903

**Comment by mspinksosu** [comment]
BOM has been added for version 2-5-0 (version A).
